version: "3"

services:
  postgres:
    image: postgis/postgis:13-3.1-alpine
    env_file: .env
    networks:
      - green-infra
    ports:
      - "5432:5432"
    volumes:
      - postgis:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    env_file: api/.env
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - green-infra

volumes:
  postgis:

networks:
  green-infra: